application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showChallengeHints: yes
  showVersionNumber: false
  showGitHubLinks: false
  welcomeBanner:
    showOnFirstStart: yes
hackingInstructor:
  isEnabled: false
ctf:
  showFlagsInNotifications: true
